//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPC_Rental_2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        public int ID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Message { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
