//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPC_Rental_2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_and_Events
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string Images { get; set; }
        public int Sale_ID { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
