#error (13:2): inconsistent cell count within the table
#error (23:1): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Feature: US04 - Book details'
#error (24:2): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'As a potential customer'
#error (25:2): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'I want to see the details of a book'
#error (26:2): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'So that I can better decide to buy it.'
#error (28:1): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Background:'
#error (29:2): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Given the following books'
#error (30:3): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got '| Author                         | Title                                                   | Price |'
#error (31:3): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got '| Gojko Adzic                    | Specification By Example                                | 12.20 |'
#error (32:3): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got '| Eckhart Tolle                  | The Power of Now                                        | 12.58 |'
#error (33:3): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got '| Jeff Sutherland                | Scrum: The Art of Doing Twice the Work in Half the Time | 16.73 |'